config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  resources :lawyers
  root to: 'meetings#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lawyer.rb
class Lawyer < ApplicationRecord
  belongs_to :user
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lawyers, dependent: :destroy
  has_many :meetings, dependent: :destroy

def username
  return self.email.split('@')[0].capitalize
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lawyers_controller.rb
class LawyersController < ApplicationController
  before_action :set_lawyer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /lawyers
  # GET /lawyers.json
  def index
    @lawyers = Lawyer.all
  end

  # GET /lawyers/1
  # GET /lawyers/1.json
  def show
  end

  # GET /lawyers/new
  def new
    @lawyer = Lawyer.new
  end

  # GET /lawyers/1/edit
  def edit
  end

  # POST /lawyers
  # POST /lawyers.json
  def create
    @lawyer = Lawyer.new(lawyer_params)
    @lawyer.user = current_user

    respond_to do |format|
      if @lawyer.save
        format.html { redirect_to @lawyer, notice: 'Lawyer was successfully created.' }
        format.json { render :show, status: :created, location: @lawyer }
      else
        format.html { render :new }
        format.json { render json: @lawyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lawyers/1
  # PATCH/PUT /lawyers/1.json
  def update
    respond_to do |format|
      if @lawyer.update(lawyer_params)
        format.html { redirect_to @lawyer, notice: 'Lawyer was successfully updated.' }
        format.json { render :show, status: :ok, location: @lawyer }
      else
        format.html { render :edit }
        format.json { render json: @lawyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lawyers/1
  # DELETE /lawyers/1.json
  def destroy
    @lawyer.destroy
    respond_to do |format|
      format.html { redirect_to lawyers_url, notice: 'Lawyer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lawyer
      @lawyer = Lawyer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lawyer_params
      params.require(:lawyer).permit(:name)
    end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = current_user.meetings.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.user_id = current_user.id

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :end_time, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def readable_time(time)
    time.strftime("%b %d, %I:%M%P")
  end

  def author_of(record)
    user_signed_in? && current_user.id == record.user_id
  end

  def admin?
    user_signed_in? && current_user.admin?
  end
  
end

app/helpers/lawyers_helper.rb
module LawyersHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/lawyers/_form.html.erb
<%= form_with(model: lawyer, local: true) do |form| %>
  <% if lawyer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lawyer.errors.count, "error") %> prohibited this lawyer from being saved:</h2>

      <ul>
        <% lawyer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
        <label for="username" class="text-info">Name:</label><br>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit nil, class: 'btn btn-info btn-md'%>
  </div>
<% end %>

app/views/lawyers/edit.html.erb
<div class="card" style="width: 50rem;">
  <h1>Editing Lawyer</h1>

<%= render 'form', lawyer: @lawyer %>
<br>
<%= link_to 'Show', @lawyer %>
</div>

app/views/lawyers/index.html.erb
<% if current_user && current_user.admin %>

<%= link_to 'New Lawyer', new_lawyer_path, class: 'btn btn-success btn-md mr-4', style: 'float: right' %>

<% end %>
<br>
<div class="m-4">
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">User</th>
      <% if current_user && current_user.admin %>
      <th scope="col">Edit</th>
      <th scope="col">Back</th>
      <th scope="col">Delete</th>
      <% else %>
      <th scope="col">Show</th>
      <% end %>

    </tr>
  </thead>
  <tbody>
      <% @lawyers.each do |lawyer| %>
        <tr>
          <td><%= lawyer.name %></td>
          <td><%= lawyer.user.username %></td>
          <td><%= link_to 'Show', lawyer %></td>
          <% if current_user && current_user.admin %>
          <td><%= link_to 'Edit', edit_lawyer_path(lawyer) %></td>
          <td><%= link_to 'Delete', lawyer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/lawyers/new.html.erb
<div class="card" style="width: 50rem;">
<h1>New Lawyer</h1>

<%= render 'form', lawyer: @lawyer %>
<%= link_to 'Back', lawyers_path %>
</div>

app/views/lawyers/show.html.erb
<div class="m-4">
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Username</th>
      <% if current_user && current_user.admin %>
      <th scope="col">Edit</th>
      <% end %>
      <th scope="col">Back</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @lawyer.name %></td>
      <td><%= @lawyer.user.username %></td>
      <% if current_user && current_user.admin %>
      <td><%= link_to 'Edit', edit_lawyer_path(@lawyer) %></td>
      <% end %>
      <td><%= link_to 'Back', lawyers_path %></td>
    </tr>
  </tbody>
</table>

app/views/layouts/_alert.html.erb
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pao System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <header>
     <%= render 'layouts/navigation' %>
   </header>
    <%= render 'layouts/alert' %>
    <%= yield %>
  </body>
</html>

app/views/meetings/_calendar.html.erb
<%= month_calendar events: meetings do |date, meetings| %>
  <%= date %>

  <% meetings.each do |meeting| %>

  <div>
    <%= link_to meeting.name, meeting, class: "link" %>
  </div>
  <% end %>
<% end %>

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% meeting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
      <label for="username" class="text-info">Name:</label><br>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

    <div class="form-group">
        <label for="start_time" class="text-info">Start Time:</label><br>
    <%= form.datetime_select :start_time, class:'form-control' %>
  </div>

    <div class="form-group">
        <label for="end_time" class="text-info">End Time:</label><br>
    <%= form.datetime_select :end_time,  class:'form-control'  %>
  </div>
  <div class="form-group actions">
    <%= form.submit nil, class: 'btn btn-info btn-md' %>
  </div>
<% end %>

app/views/meetings/_meetings_cta.html.erb
<div class="max-w-md my-10 m-4 p-12 lg:p-16 bg-white rounded border border-grey-light text-center shadow">

  <%= image_tag "logos/work.jpg", alt: "logo", width: 500, class: "mb-4 mt-2" %>
  <%#= link_to image_tag("logos/work.jpg"), root_path %>

  <h1 class="text-indigo-darker text-2xl mb-6">It looks like you haven't scheduled a session yet</h1>

  <%= link_to "Schedule a new session", new_meeting_path, class: "btn btn-success mb-4" %>

</div>

app/views/meetings/_meetings_landing.html.erb
<div class="bg-white p-10 border rounded">
  <div id="calendar" class="tab-panel m-4 active">
    <div class="row">
      <div class="col-8">
        <h2 class="mb-4">Schedule for this month</h2>
      </div>
      <div class="col-4">
        <%= link_to "Schedule a new session", new_meeting_path, class: "btn btn-success", style: 'float: right'%>
      </div>
  </div>
    <div id="meeting-calendar">
      <%= render "calendar", meetings: meetings %>
    </div>
  </div>
</div>

app/views/meetings/edit.html.erb
<div class="card" style="width: 50rem;">

<h1 class="text-center">Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %>

</div>

app/views/meetings/index.html.erb
<div class="container m-auto my-4">

  <% unless current_user.meetings.any? %>

    <%= render "meetings_cta" %>

  <% else %>

    <%= render "meetings_landing", meetings: @meetings %>

  <% end %>

</div>

app/views/meetings/new.html.erb
<div class="card" style="width: 50rem;">
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>
</div>

app/views/meetings/show.html.erb
<div class="m-4">
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Start Time</th>
      <th scope="col">End Time</th>
      <th scope="col">Edit</th>
      <th scope="col">Back</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @meeting.name %></td>
      <td><%= @meeting.start_time %></td>
      <td><%= @meeting.end_time %></td>
      <td><%= link_to 'Edit', edit_meeting_path(@meeting) %></td>
      <td><%= link_to 'Back', meetings_path %></td>
      <td><%= link_to 'Delete', @meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  </tbody>
</table>
</div>

app/views/pages/home.html.erb
<center>
<div class="card text-dark bg-light mb-4" style="max-width: 60rem;">
  <div class="card-header text-left">Header</div>
  <div class="card-body">
    <h5 class="card-title text-left">Light card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
</div>
</center>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <%= link_to 'PAO', root_path, style: 'color: white' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <ul class="navbar-nav d-flex">

      <% if current_user %>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to 'Schedule', root_path, style: 'color: white', class: 'nav-link active' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Lawyer', lawyers_path , style: 'color: white', class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Client', root_path, style: 'color: white', class: 'nav-link' %>
          </li>
          <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, style: 'color: red', class: 'nav-link' %>
            </li>
        </ul>
      </div>



      <% else %>

      <li class="nav-item">
        <%= link_to 'Sign in', new_user_session_path, style: 'color: white', class: 'nav-link' %>
      </li>

          <% end %>
    </ul>
  </div>
</nav>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <div class="row mb-2">
      <div class="col-2">
        <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view, class: "btn btn-primary mb-auto", style: 'float:left', id: "previous-month"  %>
      </div>
      <div class="col-8">
        <center>
          <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
          </center>
      </div>
      <div class="col-2">
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view, class: "btn btn-primary mb-auto", style: 'float: right', id: "next-month"  %>
      </div>
    </div>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
                <span class="text-sm text-grey-darker"><% passed_block.call day.strftime("%d"), sorted_events.fetch(day, []) %></span>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>